name: 自动搜索并验证API密钥

on:
  workflow_dispatch:
  schedule:
    # 每天北京时间 0:30，对应 UTC 16:30
    - cron: '30 16 * * *'

jobs:
  search-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 设置 Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 运行密钥搜索脚本
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python search_keys.py

      - name: 验证搜索到的API密钥有效性
        run: python check_gemini.py

      - name: 提交并推送结果
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: 自动更新并验证Gemini API密钥"
          file_pattern: "api.txt valid_gemini_keys.txt invalid_keys.txt"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
