name: 搜索并验证最新 API 密钥

on:
  workflow_dispatch:
  schedule:
    - cron: '30 16 * * *' # 每天 北京时间 0:30 (UTC 16:30)

jobs:
  # 第一个任务：搜索并提交最新的 api.txt
  search:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 设置 Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 运行搜索脚本
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python search_keys.py

      - name: 提交最新 api.txt
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: 更新最新 API 列表"
          file_pattern: "api.txt"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"

  # 第二个任务：验证最新的 API 密钥（依赖 search 任务）
  validate:
    runs-on: ubuntu-latest
    needs: search
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 设置 Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 验证 API 密钥有效性
        run: python check_gemini.py

      - name: 提交验证结果
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: 验证最新 API 密钥"
          file_pattern: "valid_gemini_keys.txt invalid_keys.txt"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
